#!/bin/sh

# ── Ensure writable directories exist ──
mkdir -p \
    storage/app/public \
    storage/app/private \
    storage/framework/cache/data \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs \
    bootstrap/cache

chown -R www-data:www-data storage bootstrap/cache 2>/dev/null || true

# ── Storage symlink ──
ln -sfn /app/storage/app/public /app/public/storage

# ── Clear compiled caches (safe on every deploy) ──
rm -f bootstrap/cache/*.php

# ── Copy .env.example → .env if no .env exists yet ──
if [ ! -f .env ]; then
    cp .env.example .env
    # Force skip install wizard in Docker — setup is handled by this entrypoint
    sed -i 's/^SKIP_INSTALL_WIZARD=.*/SKIP_INSTALL_WIZARD=true/' .env
    echo "[entrypoint] Created .env from .env.example (SKIP_INSTALL_WIZARD=true)"
fi

# ── Generate APP_KEY if not set ──
if [ -z "$APP_KEY" ] && ! grep -qE '^APP_KEY=.+' .env 2>/dev/null; then
    php artisan key:generate --force --no-interaction
    echo "[entrypoint] Generated APP_KEY"
fi

# ── Ensure public/index.php exists (app uses root index.php) ──
if [ ! -f public/index.php ] && [ -f index.php ]; then
    cat > public/index.php <<'PHPEOF'
<?php
// Generated by docker-entrypoint — delegates to /app/index.php
chdir(dirname(__DIR__));
require __DIR__ . '/../index.php';
PHPEOF
    echo "[entrypoint] Created public/index.php wrapper"
fi

# ── Run migrations (idempotent — safe on redeploy) ──
echo "[entrypoint] Running migrations..."

# Detect existing database without migrations table (e.g. set up via install wizard).
# Uses raw PDO — no Laravel bootstrap needed, so no chance of silent failure.
# Reads DB credentials from system env vars first, then falls back to .env file.
php -r "
    // Parse .env file for fallback values
    \$envVars = [];
    if (is_file('/app/.env')) {
        foreach (file('/app/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as \$line) {
            if (str_starts_with(trim(\$line), '#')) continue;
            if (strpos(\$line, '=') === false) continue;
            [\$k, \$v] = explode('=', \$line, 2);
            \$envVars[trim(\$k)] = trim(trim(\$v), '\"\'');
        }
    }

    \$host = getenv('DB_HOST') ?: (\$envVars['DB_HOST'] ?? '127.0.0.1');
    \$port = getenv('DB_PORT') ?: (\$envVars['DB_PORT'] ?? '3306');
    \$db   = getenv('DB_DATABASE') ?: (\$envVars['DB_DATABASE'] ?? 'mailpurse');
    \$user = getenv('DB_USERNAME') ?: (\$envVars['DB_USERNAME'] ?? 'root');
    \$pass = getenv('DB_PASSWORD') ?: (\$envVars['DB_PASSWORD'] ?? '');

    echo \"[entrypoint] DB connect: \$user@\$host:\$port/\$db\n\";

    try {
        \$pdo = new PDO(\"mysql:host=\$host;port=\$port;dbname=\$db;charset=utf8mb4\", \$user, \$pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_TIMEOUT => 10,
        ]);

        \$tables = \$pdo->query(\"SHOW TABLES\")->fetchAll(PDO::FETCH_COLUMN);

        \$hasUsers = in_array('users', \$tables);
        \$hasMigrations = in_array('migrations', \$tables);

        echo '[entrypoint] DB tables found: ' . count(\$tables) . \"\n\";
        echo '[entrypoint] Tables: ' . implode(', ', \$tables) . \"\n\";

        if (\$hasUsers && !\$hasMigrations) {
            echo \"[entrypoint] Existing DB without migrations table — creating and seeding it\n\";

            \$pdo->exec(\"CREATE TABLE IF NOT EXISTS migrations (
                id int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
                migration varchar(255) NOT NULL,
                batch int NOT NULL
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\");

            // Only mark migrations as done if their target table actually exists
            \$stmt = \$pdo->prepare('INSERT INTO migrations (migration, batch) VALUES (?, 1)');
            \$count = 0;
            foreach (glob('/app/database/migrations/*.php') as \$file) {
                \$name = basename(\$file, '.php');
                // Extract table name from migration filename pattern: *_create_TABLENAME_table
                if (preg_match('/create_(.+)_table\$/', \$name, \$m)) {
                    if (!in_array(\$m[1], \$tables)) {
                        continue; // table doesn't exist, let migrate create it
                    }
                }
                // For non-create migrations (alter, add column, etc), mark as done
                // only if related table exists
                if (preg_match('/(?:add|update|modify|alter|drop)_.+(?:to|from|in|on)_(.+)_table\$/', \$name, \$m)) {
                    if (!in_array(\$m[1], \$tables)) {
                        continue;
                    }
                }
                \$stmt->execute([\$name]);
                \$count++;
            }
            echo \"[entrypoint] Seeded \$count migration records (skipped missing tables)\n\";
        } elseif (\$hasMigrations) {
            // Verify migrations table is accurate — check if it claims tables exist that don't
            \$recorded = \$pdo->query(\"SELECT migration FROM migrations\")->fetchAll(PDO::FETCH_COLUMN);
            \$mismatch = false;
            foreach (\$recorded as \$mig) {
                if (preg_match('/create_(.+)_table\$/', \$mig, \$m)) {
                    if (!in_array(\$m[1], \$tables)) {
                        \$mismatch = true;
                        break;
                    }
                }
            }
            if (\$mismatch) {
                echo \"[entrypoint] Migrations table is stale (records tables that don't exist) — rebuilding\n\";
                \$pdo->exec(\"DROP TABLE migrations\");
                \$pdo->exec(\"CREATE TABLE migrations (
                    id int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    migration varchar(255) NOT NULL,
                    batch int NOT NULL
                ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\");
                \$stmt = \$pdo->prepare('INSERT INTO migrations (migration, batch) VALUES (?, 1)');
                \$count = 0;
                foreach (glob('/app/database/migrations/*.php') as \$file) {
                    \$name = basename(\$file, '.php');
                    if (preg_match('/create_(.+)_table\$/', \$name, \$m)) {
                        if (!in_array(\$m[1], \$tables)) {
                            continue;
                        }
                    }
                    if (preg_match('/(?:add|update|modify|alter|drop)_.+(?:to|from|in|on)_(.+)_table\$/', \$name, \$m)) {
                        if (!in_array(\$m[1], \$tables)) {
                            continue;
                        }
                    }
                    \$stmt->execute([\$name]);
                    \$count++;
                }
                echo \"[entrypoint] Rebuilt migrations table with \$count records\n\";
            } else {
                echo \"[entrypoint] Migrations table looks correct — running incremental migrations\n\";
            }
        } else {
            echo \"[entrypoint] Fresh database — migrations will create all tables\n\";
        }
    } catch (Throwable \$e) {
        echo '[entrypoint] DB detection error: ' . \$e->getMessage() . \"\n\";
    }
" 2>&1

php artisan migrate --force --no-interaction || echo "[entrypoint] WARNING: migrations failed — continuing startup"

# ── First-time install: create admin + mark installed ──
INSTALLED_FLAG="storage/app/private/installed.json"
if [ ! -f "$INSTALLED_FLAG" ]; then
    echo "[entrypoint] First deploy detected — running initial setup..."

    # Create admin user if env vars are provided
    if [ -n "$ADMIN_EMAIL" ] && [ -n "$ADMIN_PASSWORD" ]; then
        php artisan admin:create "$ADMIN_EMAIL" \
            --first="${ADMIN_FIRST_NAME:-Admin}" \
            --last="${ADMIN_LAST_NAME:-User}" \
            --password="$ADMIN_PASSWORD" \
            --verify || echo "[entrypoint] WARNING: admin creation had errors — continuing"
        echo "[entrypoint] Admin user created: $ADMIN_EMAIL"
    else
        echo "[entrypoint] WARNING: ADMIN_EMAIL and ADMIN_PASSWORD not set — skipping admin creation."
        echo "[entrypoint] You can create an admin later with: php artisan admin:create <email>"
    fi

    # Create storage link
    php artisan storage:link 2>/dev/null || true

    # Mark as installed so the wizard is skipped
    mkdir -p storage/app/private
    echo "{\"installed_at\":\"$(date -u +%Y-%m-%dT%H:%M:%S+00:00)\",\"method\":\"docker\"}" > "$INSTALLED_FLAG"
    echo "[entrypoint] Marked as installed"
fi

# ── Clear all caches to ensure runtime env vars are used ──
php artisan config:clear --no-interaction 2>/dev/null || true
php artisan route:clear --no-interaction 2>/dev/null || true
php artisan view:clear --no-interaction 2>/dev/null || true
echo "[entrypoint] Caches cleared"

# ── Start cron daemon (for schedule:run every minute) ──
echo "* * * * * cd /app && php artisan schedule:run >> /dev/null 2>&1" | crontab -
cron 2>/dev/null &
echo "[entrypoint] Cron started"

# ── Start queue worker in background ──
php artisan queue:work --queue=campaigns,email-validation,default \
    --sleep=3 --tries=3 --timeout=300 --max-jobs=1000 --max-time=3600 &
echo "[entrypoint] Queue worker started"

# ── Start PHP built-in server ──
echo "[entrypoint] Starting web server on port ${PORT:-8000}..."
exec php -S 0.0.0.0:${PORT:-8000} server.php
