#!/bin/sh

# ── Ensure writable directories exist ──
mkdir -p \
    storage/app/public \
    storage/app/private \
    storage/framework/cache/data \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs \
    bootstrap/cache

chown -R www-data:www-data storage bootstrap/cache 2>/dev/null || true

# ── Storage symlink ──
ln -sfn /app/storage/app/public /app/public/storage

# ── Clear compiled caches (safe on every deploy) ──
rm -f bootstrap/cache/*.php

# ── Copy .env.example → .env if no .env exists yet ──
if [ ! -f .env ]; then
    cp .env.example .env
    # Force skip install wizard in Docker — setup is handled by this entrypoint
    sed -i 's/^SKIP_INSTALL_WIZARD=.*/SKIP_INSTALL_WIZARD=true/' .env
    echo "[entrypoint] Created .env from .env.example (SKIP_INSTALL_WIZARD=true)"
fi

# ── Generate APP_KEY if not set ──
if [ -z "$APP_KEY" ] && ! grep -qE '^APP_KEY=.+' .env 2>/dev/null; then
    php artisan key:generate --force --no-interaction
    echo "[entrypoint] Generated APP_KEY"
fi

# ── Ensure public/index.php exists (app uses root index.php) ──
if [ ! -f public/index.php ] && [ -f index.php ]; then
    cat > public/index.php <<'PHPEOF'
<?php
// Generated by docker-entrypoint — delegates to /app/index.php
chdir(dirname(__DIR__));
require __DIR__ . '/../index.php';
PHPEOF
    echo "[entrypoint] Created public/index.php wrapper"
fi

# ── Run migrations (idempotent — safe on redeploy) ──
echo "[entrypoint] Running migrations..."

# Detect existing database without migrations table (e.g. set up via install wizard).
# Uses raw PDO — no Laravel bootstrap needed, so no chance of silent failure.
php -r "
    \$host = getenv('DB_HOST') ?: '127.0.0.1';
    \$port = getenv('DB_PORT') ?: '3306';
    \$db   = getenv('DB_DATABASE') ?: 'mailpurse';
    \$user = getenv('DB_USERNAME') ?: 'root';
    \$pass = getenv('DB_PASSWORD') ?: '';

    try {
        \$pdo = new PDO(\"mysql:host=\$host;port=\$port;dbname=\$db;charset=utf8mb4\", \$user, \$pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_TIMEOUT => 10,
        ]);

        \$tables = \$pdo->query(\"SHOW TABLES\")->fetchAll(PDO::FETCH_COLUMN);

        \$hasUsers = in_array('users', \$tables);
        \$hasMigrations = in_array('migrations', \$tables);

        echo '[entrypoint] DB tables found: ' . count(\$tables) . \"\n\";

        if (\$hasUsers && !\$hasMigrations) {
            echo \"[entrypoint] Existing DB without migrations table — creating and seeding it\n\";

            // Create the migrations table
            \$pdo->exec(\"CREATE TABLE migrations (
                id int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
                migration varchar(255) NOT NULL,
                batch int NOT NULL
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\");

            // Seed all current migration files as already run
            \$stmt = \$pdo->prepare('INSERT INTO migrations (migration, batch) VALUES (?, 1)');
            \$count = 0;
            foreach (glob('/app/database/migrations/*.php') as \$file) {
                \$name = basename(\$file, '.php');
                \$stmt->execute([\$name]);
                \$count++;
            }
            echo \"[entrypoint] Seeded \$count migration records\n\";
        } elseif (!\$hasUsers && !\$hasMigrations) {
            echo \"[entrypoint] Fresh database — migrations will create all tables\n\";
        } else {
            echo \"[entrypoint] Migrations table exists — running incremental migrations\n\";
        }
    } catch (Throwable \$e) {
        echo '[entrypoint] DB detection error: ' . \$e->getMessage() . \"\n\";
    }
" 2>&1

php artisan migrate --force --no-interaction || echo "[entrypoint] WARNING: migrations failed — continuing startup"

# ── First-time install: create admin + mark installed ──
INSTALLED_FLAG="storage/app/private/installed.json"
if [ ! -f "$INSTALLED_FLAG" ]; then
    echo "[entrypoint] First deploy detected — running initial setup..."

    # Create admin user if env vars are provided
    if [ -n "$ADMIN_EMAIL" ] && [ -n "$ADMIN_PASSWORD" ]; then
        php artisan admin:create "$ADMIN_EMAIL" \
            --first="${ADMIN_FIRST_NAME:-Admin}" \
            --last="${ADMIN_LAST_NAME:-User}" \
            --password="$ADMIN_PASSWORD" \
            --verify || echo "[entrypoint] WARNING: admin creation had errors — continuing"
        echo "[entrypoint] Admin user created: $ADMIN_EMAIL"
    else
        echo "[entrypoint] WARNING: ADMIN_EMAIL and ADMIN_PASSWORD not set — skipping admin creation."
        echo "[entrypoint] You can create an admin later with: php artisan admin:create <email>"
    fi

    # Create storage link
    php artisan storage:link 2>/dev/null || true

    # Mark as installed so the wizard is skipped
    mkdir -p storage/app/private
    echo "{\"installed_at\":\"$(date -u +%Y-%m-%dT%H:%M:%S+00:00)\",\"method\":\"docker\"}" > "$INSTALLED_FLAG"
    echo "[entrypoint] Marked as installed"
fi

# ── Clear all caches to ensure runtime env vars are used ──
php artisan config:clear --no-interaction 2>/dev/null || true
php artisan route:clear --no-interaction 2>/dev/null || true
php artisan view:clear --no-interaction 2>/dev/null || true
echo "[entrypoint] Caches cleared"

# ── Start cron daemon (for schedule:run every minute) ──
echo "* * * * * cd /app && php artisan schedule:run >> /dev/null 2>&1" | crontab -
cron 2>/dev/null &
echo "[entrypoint] Cron started"

# ── Start queue worker in background ──
php artisan queue:work --queue=campaigns,email-validation,default \
    --sleep=3 --tries=3 --timeout=300 --max-jobs=1000 --max-time=3600 &
echo "[entrypoint] Queue worker started"

# ── Start PHP built-in server ──
echo "[entrypoint] Starting web server on port ${PORT:-8000}..."
exec php -S 0.0.0.0:${PORT:-8000} server.php
